// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://ansghzbqyauxrrmizvax.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImFuc2doemJxeWF1eHJybWl6dmF4Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTg0MzA5OTcsImV4cCI6MjA3NDAwNjk5N30.B_bCXnwdGnuzM-gMELT89cWqZlNjMwQKLQgtmU5_vRc";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});